"""
sedna instruction codes
"""

DEBUG_OFF = 0
DEBUG_ON = 1

SE_ERROR_RESPONSE = 100

SE_START_UP = 110
SE_SESSION_PARAMETERS = 120
SE_AUTHENTICATION_PARAMETERS = 130
SE_SEND_SESSION_PARAMETERS = 140
SE_SEND_AUTH_PARAMETERS = 150
SE_AUTHENTICATION_OK = 160
SE_AUTHENTICATION_FAILED = 170
SE_AUTHENTICATE = 90

SE_BEGIN_TRANSACTION = 210
SE_COMMIT_TRANSACTION = 220
SE_ROLLBACK_TRANSACTION = 225
SE_BEGIN_TRANSACTION_OK = 230
SE_BEGIN_TRANSACTION_FAILED = 240
SE_COMMIT_TRANSACTION_OK = 250
SE_COMMIT_TRANSACTION_FAILED = 260
SE_ROLLBACK_TRANSACTION_OK = 255
SE_ROLLBACK_TRANSACTION_FAILED = 265

SE_EXECUTE = 300
SE_EXECUTE_LONG = 301
SE_LONG_QUERY_END = 302

SE_GET_NEXT_ITEM = 310
SE_QUERY_SUCCEEDED = 320

SE_DEBUG_INFO = 325

SE_QUERY_FAILED = 330
SE_UPDATE_SUCCEEDED = 340
SE_UPDATE_FAILED = 350

SE_ITEM_PART = 360
SE_ITEM_END = 370
SE_RESULT_END = 375

SE_BULKLOAD_ERROR = 400
SE_BULKLOAD_PORTION = 410
SE_BULKLOAD_END = 420
SE_BULKLOAD_FILENAME = 430
SE_BULKLOAD_FROMSTREAM = 431
SE_BULKLOAD_SUCCEEDED = 440
SE_BULKLOAD_FAILED = 450

SE_SHOW_TIME = 451
SE_LAST_QUERY_TIME = 452

SE_CLOSE_CONNECTION = 500
SE_CLOSE_CONNECTION_OK = 510
SE_TRANSACTION_ROLLBACK_BEFORE_CLOSE = 520

# included only for completeness, though it should be easy to include :)
SE_EXECUTE_SCHEME_PROGRAM = 95

SE_SET_SESSION_OPTIONS = 530
SE_SET_SESSION_OPTIONS_OK = 540
SE_RESET_SESSION_OPTIONS = 550
SE_RESET_SESSION_OPTIONS_OK = 560

codes = {}
for name,value in globals().items():
    if isinstance(value,int):
        codes[value] = name


if __name__ == '__main__':
    print codes
