"""
sedna instruction codes
"""

DEBUG_OFF = 0
DEBUG_ON = 1

ERROR_RESPONSE = 100

START_UP = 110
SESSION_PARAMETERS = 120
AUTHENTICATION_PARAMETERS = 130
SEND_SESSION_PARAMETERS = 140
SEND_AUTH_PARAMETERS = 150
AUTHENTICATION_OK = 160
AUTHENTICATION_FAILED = 170
AUTHENTICATE = 90

BEGIN_TRANSACTION = 210
COMMIT_TRANSACTION = 220
ROLLBACK_TRANSACTION = 225
BEGIN_TRANSACTION_OK = 230
BEGIN_TRANSACTION_FAILED = 240
COMMIT_TRANSACTION_OK = 250
COMMIT_TRANSACTION_FAILED = 260
ROLLBACK_TRANSACTION_OK = 255
ROLLBACK_TRANSACTION_FAILED = 265

EXECUTE = 300
EXECUTE_LONG = 301
LONG_QUERY_END = 302

GET_NEXT_ITEM = 310
QUERY_SUCCEEDED = 320

DEBUG_INFO = 325

QUERY_FAILED = 330
UPDATE_SUCCEEDED = 340
UPDATE_FAILED = 350

ITEM_PART = 360
ITEM_END = 370
RESULT_END = 375

BULKLOAD_ERROR = 400
BULKLOAD_PORTION = 410
BULKLOAD_END = 420
BULKLOAD_FILENAME = 430
BULKLOAD_FROMSTREAM = 431
BULKLOAD_SUCCEEDED = 440
BULKLOAD_FAILED = 450

SHOW_TIME = 451
LAST_QUERY_TIME = 452

CLOSE_CONNECTION = 500
CLOSE_CONNECTION_OK = 510
TRANSACTION_ROLLBACK_BEFORE_CLOSE = 520

# included only for completeness, though it should be easy to include :)
EXECUTE_SCHEME_PROGRAM = 95

SET_SESSION_OPTIONS = 530
SET_SESSION_OPTIONS_OK = 540
RESET_SESSION_OPTIONS = 550
RESET_SESSION_OPTIONS_OK = 560

codes = {}
for name,value in globals().items():
    if isinstance(value,int):
        codes[value] = name


if __name__ == '__main__':
    print codes
